# Generated by Django 5.1.6 on 2025-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0003_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consorcio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='unidad',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
