# Generated by Django 5.1.6 on 2025-03-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0004_profile_consorcio_profile_telefono_profile_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reclamos.reclamo')),
            ],
        ),
    ]
